name: checkout
run-name: Checkout

on:
  - push

jobs:
  checkout-and-list-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: ls -la

      - name: Checkout Autom√°tico por Action
        uses: actions/checkout@v4

      # - name: Checkout Manual
      #   run: |
      #     git init
      #     git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
      #     git fetch origin 
      #     git checkout main

      - name: List files after
        run: ls -la